import os

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

HARNESS_MODE = "H2_REAL_READ_ONLY"
DRY_RUN = False if HARNESS_MODE in ["H2_READ_ONLY", "H2_REAL_READ_ONLY"] else True

SENIOR_PROVIDER = "codex"
IMPLEMENTER_PROVIDER = "antigravity"
DESIGNER_PROVIDER = "disabled"

MAX_AUTONOMOUS_REVIEW_ITERATIONS = 3
NO_PROGRESS_THRESHOLD = 2
OSCILLATION_THRESHOLD = 2

# Timeouts (in seconds)
CODEX_SMOKE_TIMEOUT_SECONDS = 300
CODEX_PLAN_TIMEOUT_SECONDS = 900
CODEX_REVIEW_TIMEOUT_SECONDS = 900
ANTIGRAVITY_TIMEOUT_SECONDS = 900

# H4-2 Quota Backoff
QUOTA_PROBE_INTERVALS_MINUTES = [30, 60, 120]
QUOTA_PROBE_MAX_INTERVAL_MINUTES = 240
SUPERVISOR_POLL_SECONDS = 30

DISCORD_ENABLED = False
VERCEL_ENABLED = False
BROWSER_QA_ENABLED = False
