import argparse
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from .approval_gate import ApprovalManager, ApprovalStatus
from .runtime_state import RuntimeStateManager, RuntimeTaskState
from .models import TaskState

def get_parser():
    parser = argparse.ArgumentParser(description="CMhelper Control CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    create_p = subparsers.add_parser("create", help="Create a new task")
    create_p.add_argument("--description", required=True, help="Task description")
    create_p.add_argument("--title", default="Autogenerated Task", help="Task title")
    
    list_p = subparsers.add_parser("list", help="List active and queued tasks")
    
    status_p = subparsers.add_parser("status", help="Get task status")
    status_p.add_argument("task_id", help="Task ID")
    
    approve_p = subparsers.add_parser("approve", help="Approve a pending action")
    approve_p.add_argument("identifier", help="Task ID or Approval ID")
    
    reject_p = subparsers.add_parser("reject", help="Reject a pending action")
    reject_p.add_argument("identifier", help="Task ID or Approval ID")

    pause_p = subparsers.add_parser("pause", help="Pause a task")
    pause_p.add_argument("task_id", help="Task ID")

    resume_p = subparsers.add_parser("resume", help="Resume a paused task")
    resume_p.add_argument("task_id", help="Task ID")
    
    return parser

def main():
    parser = get_parser()
    args = parser.parse_args()
    
    root_dir = str(Path(__file__).parent.parent)
    approval_mgr = ApprovalManager(root_dir)
    runtime_mgr = RuntimeStateManager(root_dir)
    
    if args.command == "create":
        # CMH-YYYYMMDD-UUID
        date_str = datetime.now().strftime("%Y%m%d")
        task_id = f"CMH-{date_str}-{str(uuid.uuid4())[:8]}"
        state = RuntimeTaskState(
            task_id=task_id,
            task_title=args.title,
            task_description=args.description,
            state=TaskState.QUEUED
        )
        runtime_mgr.enqueue_task(state)
        print("Task created")
        print(f"Task ID: {task_id}")
        print("State: QUEUED")

    elif args.command == "list":
        active = runtime_mgr.load_state()
        print("--- Active Task ---")
        if active:
            print(f"{active.task_id} | State: {active.state.value} | Title: {active.task_title}")
        else:
            print("None")
            
        print("\n--- Queued Tasks ---")
        queued = runtime_mgr.get_queued_tasks()
        if not queued:
            print("None")
        for q in queued:
            print(f"{q.task_id} | State: {q.state.value} | Title: {q.task_title}")
    
    elif args.command == "status":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            print(f"Task: {state.task_id}")
            print(f"State: {state.state.value}")
            print(f"Provider: {state.provider}")
            print(f"Last successful stage: {state.last_successful_stage.value if state.last_successful_stage else 'None'}")
        else:
            # Check if queued
            queued = [q for q in runtime_mgr.get_queued_tasks() if q.task_id == args.task_id]
            if queued:
                print(f"Task: {queued[0].task_id}")
                print(f"State: QUEUED")
            else:
                print(f"Task {args.task_id} not found in active or queue.")
        
        apps = approval_mgr.get_task_approvals(args.task_id)
        if apps:
            print("\n--- Approvals ---")
            for app in apps:
                print(f"[{app.approval_id}] Action: {app.action} | Status: {app.status.value}")
            
    elif args.command == "approve":
        state = runtime_mgr.load_state()
        success = approval_mgr.decide(args.identifier, approved=True)
        if success:
            print(f"Approval '{args.identifier}' granted.")
            # We don't automatically transition state here. Supervisor will handle the transition
            # once it detects the approval is APPROVED.
            # But for backward compatibility with H4 where WAITING_FOR_USER_APPROVAL was a single state:
            if state and state.state == TaskState.WAITING_FOR_USER_APPROVAL:
                print("Task is currently waiting for user approval. Supervisor will resume it shortly.")
        else:
            print(f"Failed to approve '{args.identifier}'. Make sure it is PENDING.")
            
    elif args.command == "reject":
        success = approval_mgr.decide(args.identifier, approved=False)
        if success:
            print(f"Approval '{args.identifier}' rejected.")
        else:
            print(f"Failed to reject '{args.identifier}'. Make sure it is PENDING.")

    elif args.command == "pause":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            if state.state not in [TaskState.COMPLETED, TaskState.FAILED, TaskState.PAUSED]:
                state.state = TaskState.PAUSED
                runtime_mgr.save_state(state)
                print(f"Task {args.task_id} PAUSED.")
            else:
                print(f"Task {args.task_id} cannot be paused from state {state.state.value}.")
        else:
            print("Task not found.")

    elif args.command == "resume":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            if state.state == TaskState.PAUSED:
                state.state = TaskState.RESUMING
                runtime_mgr.save_state(state)
                print(f"Task {args.task_id} marked for RESUMING.")
            else:
                print(f"Task {args.task_id} is not PAUSED.")
        else:
            print("Task not found.")

if __name__ == "__main__":
    main()
