import argparse
import sys
import uuid
import hashlib
import os
from datetime import datetime, timezone
from pathlib import Path
from .approval_gate import ApprovalManager, ApprovalStatus
from .runtime_state import RuntimeStateManager, RuntimeTaskState
from .models import TaskState
from .project_registry import ProjectRegistry

def get_parser():
    parser = argparse.ArgumentParser(description="CMhelper Control CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    create_p = subparsers.add_parser("create", help="Create a new task")
    create_p.add_argument("--project", help="Project ID")
    create_p.add_argument("--description", help="Task description")
    create_p.add_argument("--file", help="Path to markdown file containing the task description")
    create_p.add_argument("--title", default="Autogenerated Task", help="Task title")
    
    list_p = subparsers.add_parser("list", help="List active and queued tasks")
    
    status_p = subparsers.add_parser("status", help="Get task status")
    status_p.add_argument("task_id", help="Task ID")
    
    approve_p = subparsers.add_parser("approve", help="Approve a pending action")
    approve_p.add_argument("task_id", help="Task ID")
    approve_p.add_argument("approval_id", help="Approval ID")
    
    reject_p = subparsers.add_parser("reject", help="Reject a pending action")
    reject_p.add_argument("task_id", help="Task ID")
    reject_p.add_argument("approval_id", help="Approval ID")

    pause_p = subparsers.add_parser("pause", help="Pause a task")
    pause_p.add_argument("task_id", help="Task ID")

    resume_p = subparsers.add_parser("resume", help="Resume a paused task")
    resume_p.add_argument("task_id", help="Task ID")
    
    doctor_p = subparsers.add_parser("doctor", help="Check system health")
    doctor_p.add_argument("--project", help="Project ID")
    
    next_p = subparsers.add_parser("next", help="Resolve the next task")
    next_p.add_argument("--project", help="Project ID", required=True)
    next_p.add_argument("--create", action="store_true", help="Create the task if READY and HIGH confidence")
    
    return parser

def compute_hash(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()

def main():
    parser = get_parser()
    args = parser.parse_args()
    
    root_dir = str(Path(__file__).parent.parent)
    approval_mgr = ApprovalManager(root_dir)
    runtime_mgr = RuntimeStateManager(root_dir)
    registry = ProjectRegistry(root_dir)
    
    if args.command == "create":
        if not args.description and not args.file:
            print("Error: Must provide either --description or --file")
            sys.exit(1)
            
        description = args.description
        if args.file:
            file_path = Path(args.file)
            if not file_path.exists():
                print(f"Error: File {args.file} does not exist.")
                sys.exit(1)
            with open(file_path, "r", encoding="utf-8") as f:
                description = f.read().strip()
                
        if not description:
            print("Error: Empty description provided.")
            sys.exit(1)
            
        project_id = args.project
        if not project_id:
            default_proj = registry.get_default_project()
            if default_proj:
                project_id = default_proj.project_id
            else:
                print("Error: No project specified and no default project found.")
                sys.exit(1)
                
        project = registry.get_project(project_id)
        if not project:
            print(f"Error: Project '{project_id}' not found in registry.")
            sys.exit(1)
            
        # Deduplication based on hash of description
        req_hash = compute_hash(project_id + description)
        
        # Check if hash already exists in queued tasks
        queued = runtime_mgr.get_queued_tasks()
        for q in queued:
            if getattr(q, 'request_id', None) == req_hash:
                print(f"Duplicate task detected (already in queue). Task ID: {q.task_id}")
                sys.exit(0)
                
        # CMH-YYYYMMDD-UUID
        date_str = datetime.now().strftime("%Y%m%d")
        task_id = f"CMH-{date_str}-{str(uuid.uuid4())[:8]}"
        state = RuntimeTaskState(
            task_id=task_id,
            project_id=project_id,
            task_title=args.title,
            task_description=description,
            state=TaskState.QUEUED
        )
        state.request_id = req_hash
        runtime_mgr.enqueue_task(state)
        print("Task created")
        print(f"Project: {project_id}")
        print(f"Task ID: {task_id}")
        print("State: QUEUED")

    elif args.command == "list":
        active = runtime_mgr.load_state()
        print("--- Active Task ---")
        if active:
            print(f"{active.task_id} [{active.project_id}] | State: {active.state.value} | Title: {active.task_title}")
        else:
            print("None")
            
        print("\n--- Queued Tasks ---")
        queued = runtime_mgr.get_queued_tasks()
        if not queued:
            print("None")
        for q in queued:
            print(f"{q.task_id} [{getattr(q, 'project_id', 'unknown')}] | State: {q.state.value} | Title: {q.task_title}")
    
    elif args.command == "status":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            print(f"Project ID: {state.project_id}")
            print(f"Task ID: {state.task_id}")
            print(f"Description: {state.task_description}")
            print(f"State: {state.state.value}")
            print(f"Current Stage: {state.state.value}")
            print(f"Last Successful Stage: {state.last_successful_stage.value if state.last_successful_stage else 'None'}")
            print(f"Iteration: {state.iteration}")
            
            print(f"Quota Status: Provider: {state.provider or 'None'}, Waiting: {'Yes' if state.state == TaskState.WAITING_FOR_QUOTA else 'No'}, Next probe: {state.next_probe_at.isoformat() if state.next_probe_at else 'None'}")
            print(f"Last Error: {state.reason if state.reason else 'None'}")
            
            if state.blocking_approval_id:
                print(f"Blocking Approval ID: {state.blocking_approval_id}")
                print(f"Blocking Approval Action: {state.blocking_approval_action}")
        else:
            # Check if queued
            queued = [q for q in runtime_mgr.get_queued_tasks() if q.task_id == args.task_id]
            if queued:
                q = queued[0]
                print(f"Project ID: {getattr(q, 'project_id', 'unknown')}")
                print(f"Task ID: {q.task_id}")
                print(f"Description: {q.task_description}")
                print(f"State: QUEUED")
            else:
                print(f"Task {args.task_id} not found in active or queue.")
        
        apps = approval_mgr.get_task_approvals(args.task_id)
        if apps:
            print("\n--- Approvals ---")
            for app in apps:
                print(f"[{app.approval_id}] Action: {app.action} | Status: {app.status.value} | Created: {app.requested_at.isoformat()} | Expiry: {app.expires_at.isoformat()}")
            
    elif args.command == "approve":
        state = runtime_mgr.load_state()
        apps = approval_mgr.get_task_approvals(args.task_id)
        app = next((a for a in apps if a.approval_id == args.approval_id), None)
        if not app:
            print(f"Error: Approval ID '{args.approval_id}' not found for Task ID '{args.task_id}'.")
            sys.exit(1)
            
        success = approval_mgr.decide(args.approval_id, approved=True)
        if success:
            print(f"Approval '{args.approval_id}' granted for task '{args.task_id}'.")
            if state and state.state == TaskState.WAITING_FOR_USER_APPROVAL and state.blocking_approval_id == args.approval_id:
                print("Task is currently waiting for user approval. Supervisor will resume it shortly.")
        else:
            print(f"Failed to approve '{args.approval_id}'. Make sure it is PENDING.")
            
    elif args.command == "reject":
        apps = approval_mgr.get_task_approvals(args.task_id)
        app = next((a for a in apps if a.approval_id == args.approval_id), None)
        if not app:
            print(f"Error: Approval ID '{args.approval_id}' not found for Task ID '{args.task_id}'.")
            sys.exit(1)
            
        success = approval_mgr.decide(args.approval_id, approved=False)
        if success:
            print(f"Approval '{args.approval_id}' rejected for task '{args.task_id}'.")
        else:
            print(f"Failed to reject '{args.approval_id}'. Make sure it is PENDING.")

    elif args.command == "pause":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            if state.state not in [TaskState.COMPLETED, TaskState.FAILED, TaskState.PAUSED]:
                state.state = TaskState.PAUSED
                runtime_mgr.save_state(state)
                print(f"Task {args.task_id} PAUSED.")
            else:
                print(f"Task {args.task_id} cannot be paused from state {state.state.value}.")
        else:
            print("Task not found.")

    elif args.command == "resume":
        state = runtime_mgr.load_state()
        if state and state.task_id == args.task_id:
            if state.state == TaskState.PAUSED:
                state.state = TaskState.RESUMING
                runtime_mgr.save_state(state)
                print(f"Task {args.task_id} marked for RESUMING.")
            else:
                print(f"Task {args.task_id} is not PAUSED.")
        else:
            print("Task not found.")
            
    elif args.command == "doctor":
        project_id = args.project
        if not project_id:
            default_proj = registry.get_default_project()
            if default_proj:
                project_id = default_proj.project_id
            else:
                print("Error: No project specified and no default project found.")
                sys.exit(1)
                
        project = registry.get_project(project_id)
        if not project:
            print(f"Error: Project '{project_id}' not found in registry.")
            sys.exit(1)
            
        print(f"=== CMhelper Doctor ===")
        print(f"Project Config: PASS ({project.project_name})")
        print(f"Project Root: {project.resolve_root(str(registry.projects_dir))}")
        print(f"Governance Docs: {'PASS' if project.governance_docs else 'NOT_CONFIGURED'}")
        
        # Check supervisor
        import subprocess
        try:
            out = subprocess.check_output('tasklist /v', shell=True, text=True)
            sup_running = 'python' in out.lower() and 'supervisor' in out.lower()  # Just a heuristic fallback since tasklist /v truncates window title
        except Exception:
            sup_running = False
        print(f"Supervisor: {'PASS (Running/Unknown)' if sup_running else 'FAIL/UNKNOWN (Not Running)'}")
        
        # Check queue
        queued = len(runtime_mgr.get_queued_tasks())
        print(f"Queue: PASS ({queued} tasks queued)")
        
        from .quota_probe import ProviderHealthChecker
        checker = ProviderHealthChecker()
        
        codex_res = checker.check("codex")
        print(f"Codex: {codex_res.status.value}")
        
        agy_res = checker.check("antigravity")
        print(f"Antigravity: {agy_res.status.value}")
        
        import subprocess
        git_res = subprocess.run(["git", "--version"], capture_output=True, text=True)
        print(f"Git: {'PASS' if git_res.returncode == 0 else 'FAIL'}")
        
        if project.supabase.enabled:
            # We don't verify secret here to prevent AI quota or leak
            has_url = "SUPABASE_URL" in os.environ
            has_key = "SUPABASE_SERVICE_ROLE_KEY" in os.environ
            print(f"Supabase: {'PASS' if has_url and has_key else 'FAIL (Missing Secrets)'}")
        else:
            print("Supabase: NOT_CONFIGURED")
            
        if project.vercel.enabled:
            has_token = "VERCEL_TOKEN" in os.environ
            print(f"Vercel: {'PASS' if has_token else 'FAIL (Missing Token)'}")
        else:
            print("Vercel: NOT_CONFIGURED")
        if project.browser_qa.enabled:
            print("Browser QA: PASS")
        else:
            print("Browser QA: NOT_CONFIGURED")
            
        has_discord = "DISCORD_WEBHOOK_URL" in os.environ
        print(f"Discord: {'PASS' if has_discord else 'NOT_CONFIGURED'}")

    elif args.command == "next":
        project_id = args.project
        project = registry.get_project(project_id)
        if not project:
            print(f"Error: Project '{project_id}' not found in registry.")
            sys.exit(1)
            
        from .context_builder import ContextBuilder
        from .next_task_resolver import NextTaskResolver
        
        builder = ContextBuilder(root_dir)
        try:
            bundle = builder.build_context(project, registry.projects_dir)
        except Exception as e:
            print(f"Project: {project_id}\nResult: BLOCKED\nReason: Failed to build context: {e}")
            sys.exit(0)
            
        resolver = NextTaskResolver(root_dir)
        try:
            res = resolver.resolve(bundle)
        except Exception as e:
            print(f"Project: {project_id}\nResult: BLOCKED\nReason: Resolver exception: {e}")
            sys.exit(0)
            
        print(f"Project: {res.project_id}")
        print(f"Result: {res.result}")
        
        def safe_print(text):
            try:
                print(text)
            except UnicodeEncodeError:
                print(text.encode('cp949', 'replace').decode('cp949'))
                
        if res.candidate:
            c = res.candidate
            safe_print(f"Next Task:\n{c.title}\n{c.description}")
            safe_print(f"Reason: {c.reason}")
            safe_print(f"Sources: {', '.join(c.source_documents)}")
            print(f"Risk: {c.risk_level}")
            print(f"Confidence: {c.confidence}")
            print("Acceptance Criteria:")
            for ac in c.acceptance_criteria:
                safe_print(f"- {ac}")
        else:
            safe_print(f"Reason: {res.reason}")
            
        if args.create:
            if res.result == "READY" and res.candidate and res.candidate.confidence == "HIGH":
                c = res.candidate
                description = c.description
                req_hash = compute_hash(project_id + description)
                
                queued = runtime_mgr.get_queued_tasks()
                if any(getattr(q, 'request_id', None) == req_hash for q in queued):
                    print(f"Duplicate task detected (already in queue). Task not created.")
                    sys.exit(0)
                
                date_str = datetime.now().strftime("%Y%m%d")
                task_id = f"CMH-{date_str}-{str(uuid.uuid4())[:8]}"
                state = RuntimeTaskState(
                    task_id=task_id,
                    project_id=project_id,
                    task_title=c.title,
                    task_description=description,
                    state=TaskState.QUEUED
                )
                state.request_id = req_hash
                runtime_mgr.enqueue_task(state)
                print(f"\nTask created\nTask ID: {task_id}")
            else:
                print("\nTask not created (Result is not READY with HIGH confidence, or candidate missing).")

if __name__ == "__main__":
    main()
